<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2ENHKD3" ignored="0" name="Contractor_Standard_Test" tests="1" failures="1" timestamp="11 Aug 2019 08:22:49 GMT" time="10858.476" errors="0">
  <testcase name="contractorAddNewRunsheet" time="10821.831" classname="main.java.tests.contractorTests.contractorAddNewRunsheet">
    <failure type="java.lang.AssertionError" message="The new runsheet could not be added expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The new runsheet could not be added expected [true] but found [false]
at main.java.tests.contractorTests.contractorAddNewRunsheet.contractorAddNewRunsheet(contractorAddNewRunsheet.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- contractorAddNewRunsheet -->
</testsuite> <!-- Contractor_Standard_Test -->
